title: Kueh Images Classifier
description: Classify kueh images using deep learning
about:


  This is a Kueh Images Classifier using Deep Learning built on top of Pytorch.


  The project was build by Yew Teik Kheng

code: https://github.com/teikkheng/kueh_classifier

sampleImages:
  - name: pulut inti
    url: https://2.bp.blogspot.com/-9jxXzrf5bg8/VUUWhVuWdMI/AAAAAAAAPSo/4XxX4KQenEg/s1600/SSWF-PulutInti.JPG
  - name: kueh salat
    url: https://keeprecipes.com/sites/keeprecipes/files/b4_fu_ben__18.jpg
  - name: ang ku kueh
    url: https://sethlui.com/wp-content/uploads/2018/04/ji-xiang-ang-ku-kueh-3.jpg
  - name: eggplant (not in training data)
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/1280px-Solanum_melongena_24_08_2012_%281%29.JPG
  - name: table (not in training & not a food)
    url: https://image.shutterstock.com/image-photo/brown-light-wooden-round-dining-260nw-588358070.jpg 